AS00     ,BÀO NGU NH?T B?N SASHIMI
                                                                                                                                                                                                                                      ,      738000, Ðu?c ch? bi?n t? nguyên li?u tuoi ngon và tinh hoa c?a ngh? thu?t ?m th?c Nh?t B?n, m?i mi?ng sashimi bào ngu s? tan ch?y trên d?u lu?i v?i huong v? d?m dà, ng?t ngào và m?m m?i.                                                                             ,shashimisushi0
                                                                                                                                                                                                                                                ,Shashimisushi
                                                                                                                                                                                                                                                 ,        103
AS01     ,B?CH TUÔC NH?
                                                                                                                                                                                                                                                 ,      680000,V?i ch?t lu?ng tuoi ngon và v? ng?t t? nhiên, món an này s? làm say d?m v? giác c?a b?n và mang d?n m?t c?m giác xa hoa và sang tr?ng.                                                                                                                          ,shashimisushi1                                                                                                                                                                                                                                                  ,Shashimisushi                                                                                                                                                                                                                                                   ,        120
AS02     ,BÁCH TU?C TR?N GI?M
                                                                                                                                                                                                                                           ,      268000,S? k?t h?p tuy?t v?i gi?a v? chua, ng?t và mùi thom c?a gi?m t?o nên m?t tr?i nghi?m ?m th?c d?c bi?t. Thu?ng th?c món này s? mang d?n cho b?n c?m giác s?ng khoái và hài lòng.                                                                                 ,shashimisushi2                                                                                                                                                                                                                                                  ,Shashimisushi                                                                                                                                                                                                                                                   ,         23
AS03     ,B?CH TU?C U?P WASABI
                                                                                                                                                                                                                                          ,      890000,V?i b?ch tu?c u?p wasabi, b?n s? du?c tr?i nghi?m m?t huong v? cay n?ng, d?m dà và s?ng khoái. Khi k?t h?p v?i v? d?c trung c?a wasabi, món an này s? làm cho v? giác c?a b?n thêm ph?n hung ph?n và d?c dáo.                                                   ,shashimisushi3                                                                                                                                                                                                                                                  ,Shashimisushi                                                                                                                                                                                                                                                   ,         23
AS04     ,CÁ H?I S?NG
                                                                                                                                                                                                                                                   ,      990000,V?i huong v? tuoi mát, th?t m?m m?n và màu s?c h?p d?n, món cá này s? khi?n b?n thu?ng th?c nh?ng tr?i nghi?m ?m th?c d?c bi?t và d?ng c?p.                                                                                                                     ,shashimisushi4                                                                                                                                                                                                                                                  ,Shashimisushi                                                                                                                                                                                                                                                   ,         58
AS05     ,CÁ NG?, CÁ H?I, NGAO BI?N S?NG VÀ COM SUSHI T?NG H?P
                                                                                                                                                                                                          ,      238000,Ð?m chìm trong s? da d?ng và phong phú c?a cá ng?, cá h?i, ngao bi?n s?ng và com sushi t?ng h?p t?i nhà hàng cao c?p.                                                                                                                                           ,shashimisushi5                                                                                                                                                                                                                                                  ,Shashimisushi                                                                                                                                                                                                                                                   ,         56
AS06     ,10 LO?I CÁ S?NG T?NG H?P
                                                                                                                                                                                                                                      ,      238000,T? cá ng?, cá h?i, cá trích d?n các lo?i cá khác, m?i mi?ng cá s? mang d?n cho b?n huong v? tuoi mát, ngon lành và d?c dáo, kích thích v? giác và làm say d?m trái tim c?a b?n.                                                                                 ,shashimisushi6                                                                                                                                                                                                                                                  ,Shashimisushi                                                                                                                                                                                                                                                   ,         23
AS07     ,12 LOA?I CÁ S?NG T?NG H?P
                                                                                                                                                                                                                                     ,      238000,V?i ch?t lu?ng tuoi ngon và màu s?c tuoi sáng, m?i mi?ng cá s? mang d?n cho b?n m?t tr?i nghi?m ?m th?c d?ng c?p và d?c dáo.                                                                                                                                    ,shashimisushi7                                                                                                                                                                                                                                                  ,Shashimisushi                                                                                                                                                                                                                                                   ,         48
AS08     ,6 LO?I CÁ S?NG T?NG H?P
                                                                                                                                                                                                                                       ,      188000,T? cá trích, cá h?i d?n các lo?i cá khác, m?i mi?ng cá tuoi ngon s? mang d?n huong v? tinh t?, da d?ng và thú v?.                                                                                                                                               ,shashimisushi8                                                                                                                                                                                                                                                  ,Shashimisushi                                                                                                                                                                                                                                                   ,         22
AS09     ,8 LO?I CÁ S?NG T?NG H?P
                                                                                                                                                                                                                                       ,      118000,T? cá trích, cá h?i d?n các lo?i cá khác, m?i mi?ng cá s? mang d?n huong v? tuoi mát, ngon lành và d?c bi?t, kích thích v? giác và làm say d?m trái tim c?a b?n.                                                                                                ,shashimisushi9                                                                                                                                                                                                                                                  ,Shashimisushi                                                                                                                                                                                                                                                   ,         15
AS10     ,CÁ TRÍCH, CÁ H?I, B?CH TU?C S?NG VÀ COM SUSHI
                                                                                                                                                                                                                 ,      420000,M?i mi?ng sushi du?c ch? bi?n tinh t? và k?t h?p các nguyên li?u tuoi ngon, mang d?n huong v? tinh t? và d?c dáo.                                                                                                                                               ,shashimisushi10                                                                                                                                                                                                                                                 ,Shashimisushi                                                                                                                                                                                                                                                   ,         23
AS11     ,CÁ TRÍCH, CÁ H?I, TÔM NH?T, B?CH TU?C, TR?NG CS H?I S?NG VÀ COM SUSHI T?NG H?P
                                                                                                                                                                                ,      420000,Thu?ng th?c s? k?t h?p d?c dáo và huong v? phong phú c?a cá trích, cá h?i, tôm Nh?t, b?ch tu?c, tr?ng cá h?i s?ng và com sushi t?ng h?p.                                                                                                                        ,shashimisushi11                                                                                                                                                                                                                                                 ,Shashimisushi                                                                                                                                                                                                                                                   ,         23
CC00     ,CHÁO CUA
                                                                                                                                                                                                                                                      ,       80000,B?n s? du?c hòa mình trong huong v? d?c trung c?a cua, cùng v?i s? ?m áp và ng?t ngào c?a cháo. Món an này thu?ng du?c trang trí v?i các thành ph?n tuoi ngon khác nhu hành, rau mùi, tiêu, t?o nên m?t tr?i nghi?m ?m th?c tuy?t v?i.                          ,comchao0
                                                                                                                                                                                                                                                      ,Noodlerice                                                                                                                                                                                                                                                      ,         65
CC01     ,CHÁO CÁ H?I
                                                                                                                                                                                                                                                   ,       60000,S? k?t h?p hoàn h?o gi?a cá h?i tuoi ngon và cháo m?m m?n. Cá h?i thom ngon du?c ch? bi?n thành t?ng mi?ng nh?, k?t h?p v?i huong v? d?c trung c?a cháo, t?o nên m?t món an h?p d?n và ngon mi?ng.                                                              ,comchao1
                                                                                                                                                                                                                                                      ,Noodlerice                                                                                                                                                                                                                                                      ,         66
CC02     ,CHÁO HÀO 
                                                                                                                                                                                                                                                     ,       48000,Hào tuoi ngon du?c ch? bi?n thành nh?ng mi?ng nh?, k?t h?p v?i huong v? d?c dáo c?a cháo, t?o nên m?t món an thanh nh? và d?m dà.                                                                                                                               ,comchao2
                                                                                                                                                                                                                                                      ,Noodlerice                                                                                                                                                                                                                                                      ,         63
CC03     ,CHÁO NGAO
                                                                                                                                                                                                                                                     ,       45000,Mang d?n huong v? d?c bi?t c?a ngao cùng s? ?m áp và ng?t ngào c?a cháo, là m?t l?a ch?n tuy?t v?i cho nh?ng ngu?i yêu thích huong v? bi?n.                                                                                                                     ,comchao3
                                                                                                                                                                                                                                                      ,Noodlerice                                                                                                                                                                                                                                                      ,         96
CC04     ,CÁ H?I VÀ TR?NG CÁ H?I Ð?T LÊN BÁT COM SUSHI PHU?C V? KÈM SÚP MISO                                                                                                                                                                                              ,      318000,Cá h?i tuoi ngon và tr?ng cá h?i thom ngon t?o nên m?t s? k?t h?p hoàn h?o trên com sushi, mang d?n huong v? tuy?t v?i c?a cá h?i và v? ng?t c?a tr?ng cá h?i. Bên c?nh dó, súp miso thom ngon làm tang thêm huong v? và tr?i nghi?m ?m th?c c?a món an này.    ,comchao4
                                                                                                                                                                                                                                                      ,Noodlerice                                                                                                                                                                                                                                                      ,         45
CC05     ,CÁ NG? S?NG Ð?T LÊN BÁT COM SUSHI PH?C V? KÈM SÚP MISO
                                                                                                                                                                                                        ,      218000,Cá ng? s?ng tuoi ngon t?o nên s? tuoi mát và d?m dà trên com sushi, k?t h?p v?i v? thom ngon và b? du?ng c?a súp miso.                                                                                                                                          ,comchao5
                                                                                                                                                                                                                                                      ,Noodlerice                                                                                                                                                                                                                                                      ,         55
CC06     ,CÁ THU NU?NG MU?I HO?C S?T TERI
                                                                                                                                                                                                                               ,      228000,Cá thu nu?ng mu?i mang d?n huong v? d?m dà và ng?t ngào, trong khi cá thu nu?ng v?i s?t teriyaki t?o nên huong v? thom ngon và ng?t béo.                                                                                                                        ,comchao6
                                                                                                                                                                                                                                                      ,Noodlerice                                                                                                                                                                                                                                                      ,         63
CC07     ,COM CARI V?I TÔM TEMPURA
                                                                                                                                                                                                                                      ,      126000, Com du?c trang trí v?i các mi?ng tôm tuoi s?ng ch? bi?n thành tempura giòn r?m, kèm theo m?t s? rau và gia v? thom ngon.                                                                                                                                       ,comchao7
                                                                                                                                                                                                                                                      ,Noodlerice                                                                                                                                                                                                                                                      ,         89
CC08     ,COM CÁ H?I NU?NG MU?I
                                                                                                                                                                                                                                         ,      150000,Com du?c k?t h?p v?i mi?ng cá h?i tuoi ngon, du?c nu?ng v?a d? d? gi? du?c d? m?m m?n và d?m dà c?a cá. V? mu?i nh? nhàng và huong thom t? nhiên t? cá h?i t?o nên m?t món an don gi?n nhung vô cùng h?p d?n.                                                   ,comchao8
                                                                                                                                                                                                                                                      ,Noodlerice                                                                                                                                                                                                                                                      ,         56
CC09     ,COM HÀU T?M B?T RÁN
                                                                                                                                                                                                                                           ,      208000,Com du?c ch? bi?n v?i hàu tuoi ngon, du?c t?m b?t rán giòn r?m. Huong v? d?c trung c?a hàu hòa quy?n v?i l?p v? b?t giòn tan, t?o nên m?t tr?i nghi?m ?m th?c thú v? và dáng nh?.                                                                               ,comchao9
                                                                                                                                                                                                                                                      ,Noodlerice                                                                                                                                                                                                                                                      ,         22
CC10     ,COM H?P LO?I A
                                                                                                                                                                                                                                                ,      288000,Com h?p g?m com tr?ng m?m m?n và m?t s? món an di kèm nhu th?t gà nu?ng, cá h?i nu?ng, rau xà lách, tr?ng, và nhi?u lo?i rau s?ng khác.                                                                                                                         ,comchao10
                                                                                                                                                                                                                                                     ,Noodlerice                                                                                                                                                                                                                                                      ,         22
CC11     ,COM H?P LO?I B
                                                                                                                                                                                                                                                ,      288000,Com h?p bao g?m com tr?ng m?m m?n và m?t s? món an di kèm nhu th?t heo xào, cá h?i nu?ng, rau xà lách, tr?ng, và m?t s? lo?i rau s?ng khác.                                                                                                                     ,comchao11
                                                                                                                                                                                                                                                     ,Noodlerice                                                                                                                                                                                                                                                      ,         99
DR01     ,COCKTAIL TÍM HUY?N ?O
                                                                                                                                                                                                                                         ,       78000,V?i s?c tím mê ho?c và huong v? d?c dáo, cocktail này s? mang d?n cho b?n m?t tr?i nghi?m thú v? và lôi cu?n, nhu nh?ng con mo tím ?n ch?a nh?ng di?u k? di?u.                                                                                                  ,ruou1                                                                                                                                                                                                                                                           ,Drink                                                                                                                                                                                                                                                           ,         45
DR02     ,SODA CHANH KIWI
                                                                                                                                                                                                                                               ,       48000,Hòa quy?n gi?a huong v? tuoi mát c?a chanh và huong thom c?a kiwi, nu?c soda chanh kiwi s? làm d?u di cái nóng ngày hè và mang l?i c?m giác s?ng khoái và tràn d?y nang lu?ng.                                                                                  ,ruou2                                                                                                                                                                                                                                                           ,Drink                                                                                                                                                                                                                                                           ,         85
DR03     ,BLUEBERRY COCKTAIL
                                                                                                                                                                                                                                            ,       58000,V?i màu xanh l?p lánh và huong v? d?c dáo, blue cocktail s? là di?m nh?n d?c bi?t t?i nhà hàng chu´ng tôi. Thu?ng th?c ly cocktail này là tr?i nghi?m c?a s? thú v? và phong cách.                                                                              ,ruou3                                                                                                                                                                                                                                                           ,Drink                                                                                                                                                                                                                                                           ,         89
DR04     ,TRA` HOA ÐÂ?U BIÊ´C  DI?U NHE? 
                                                                                                                                                                                                                               ,       50000,Trà hoa d?u bi?c d?u nh? là m?t món d? u?ng thu?ng h?ng t?i nhà hàng cao c?p. V?i màu s?c và huong v? tinh t? c?a hoa d?u bi?c, trà này s? mang d?n cho b?n m?t c?m giác thu thái và thú v?.                                                                    ,ruou4                                                                                                                                                                                                                                                           ,Drink                                                                                                                                                                                                                                                           ,         45
DR05     ,MATCHA LATTE
                                                                                                                                                                                                                                                  ,       48000,V?i huong v? d?c trung c?a trà matcha, k?t h?p v?i s?a và du?ng, dây là m?t th?c u?ng thu?ng h?ng dem l?i s? bình yên và s? ng?t ngào.                                                                                                                          ,ruou5                                                                                                                                                                                                                                                           ,Drink                                                                                                                                                                                                                                                           ,         52
DR06     ,RU?U MO CHUNG CÂ´T
                                                                                                                                                                                                                                            ,       96000,Ru?u mo chung c?t là m?t lo?i ru?u d?c bi?t du?c chung c?t t? qu? mo thu?ng h?ng. V?i huong v? tinh t? và mê ho?c, món này s? mang d?n cho b?n m?t tr?i nghi?m ?m th?c cao c?p và d?c dáo.                                                                      ,ruou6                                                                                                                                                                                                                                                           ,Drink                                                                                                                                                                                                                                                           ,         75
DR07     ,OSAKE THUO?NG HA?NG
                                                                                                                                                                                                                                           ,      118000,V?i huong v? tinh t? và s? thanh l?ch, osake này là s? l?a ch?n hoàn h?o cho nh?ng ai mu?n tr?i nghi?m huong v? truy?n th?ng c?a Nh?t B?n.                                                                                                                      ,ruou7                                                                                                                                                                                                                                                           ,Drink                                                                                                                                                                                                                                                           ,        112
DR08     ,SINH T? CHANH LEO TUOI MA´T
                                                                                                                                                                                                                                   ,       58000, V?i huong v? t? nhiên và mát l?nh c?a chanh leo, sinh t? này s? mang l?i s? s?ng khoái và c?m giác tuoi m?i cho b?n.                                                                                                                                           ,ruou8                                                                                                                                                                                                                                                           ,Drink                                                                                                                                                                                                                                                           ,         36
DR09     ,HIBICUS DUA H?U CHANH ÐÀO 
                                                                                                                                                                                                                                    ,       48000,Hòa quy?n gi?a huong thom c?a hoa b?p gi?m, v? ng?t ngào c?a dua h?u và huong v? tuoi mát c?a chanh dào, dây là m?t ly hibiscus dua h?u chanh dào d?c dáo và h?p d?n.                                                                                           ,ruou9                                                                                                                                                                                                                                                           ,Drink                                                                                                                                                                                                                                                           ,         75
DR10     ,COCKTAIL DÂU NGO?T NGA`O

                                                                                                                                                                                                                                    ,       78000,Cocktail dâu ng?t ngào s? làm say d?m trái tim b?n v?i huong v? tuoi mát và ng?t ngào c?a dâu. V?i màu s?c tuoi sáng và c?m giác mát l?nh trên d?u lu?i, dây là m?t món d? u?ng tuy?t v?i d? thu?ng th?c.                                                       ,ruou10                                                                                                                                                                                                                                                          ,Drink                                                                                                                                                                                                                                                           ,         32
MK00     ,TR?NG H?P H?I S?N
                                                                                                                                                                                                                                             ,       80000,Tr?ng du?c h?p chín và k?t h?p v?i các lo?i h?i s?n nhu tôm, m?c, cá... t?o nên m?t món an thom ngon và d?c dáo.                                                                                                                                                ,monankhac0
                                                                                                                                                                                                                                                    ,Tempura                                                                                                                                                                                                                                                         ,         45
MK01     ,TR?NG CU?N LUON
                                                                                                                                                                                                                                               ,       18000,Tr?ng cu?n luon là m?t món an d?c dáo và ngon mi?ng. L?p tr?ng du?c cu?n quanh nhân luon và du?c chiên giòn, t?o nên m?t huong v? thom ngon và h?p d?n.                                                                                                         ,monankhac1
                                                                                                                                                                                                                                                    ,Tempura                                                                                                                                                                                                                                                         ,         65
MK02     ,TÔM TEMPURA ÁP CH?O VÀ TR?NG
                                                                                                                                                                                                                                  ,      128000,Tôm tempura du?c áp ch?o v?i tr?ng, t?o nên m?t huong v? d?c trung và ngon mi?ng. Món an này thu?ng du?c kèm v?i nu?c s?t d? tang thêm huong v?.                                                                                                                ,monankhac2
                                                                                                                                                                                                                                                    ,Tempura                                                                                                                                                                                                                                                         ,         36
MK03     ,TH?T BÒ XÀO N?M
                                                                                                                                                                                                                                               ,      128000,Th?t bò du?c xào chín m?m, k?t h?p v?i các lo?i n?m tuoi ngon, t?o nên m?t huong v? d?c dáo và thú v?.                                                                                                                                                          ,monankhac3
                                                                                                                                                                                                                                                    ,Tempura                                                                                                                                                                                                                                                         ,         76
MK04     ,TH?T BÒ ÁP CH?O S?T T?I
                                                                                                                                                                                                                                       ,      158000,Th?t bò du?c áp ch?o giòn và k?t h?p v?i s?t t?i thom ngon, t?o nên m?t huong v? d?c trung và h?p d?n.                                                                                                                                                          ,monankhac4
                                                                                                                                                                                                                                                    ,Tempura                                                                                                                                                                                                                                                         ,         95
MK05     ,TH? BA CH? XÀO B?P C?I ?T
                                                                                                                                                                                                                                     ,      108000,Th?t ba ch? du?c xào chín m?m, k?t h?p v?i b?p c?i và ?t t?o nên m?t huong v? d?c trung và ngon mi?ng.                                                                                                                                                          ,monankhac5
                                                                                                                                                                                                                                                    ,Tempura                                                                                                                                                                                                                                                         ,         45
MK06     ,SÚP KONBU N?U Ð?U PH? NH?T RÁN
                                                                                                                                                                                                                                ,       96000,Súp du?c n?u t? nu?c dùng konbu và kèm theo d?u ph? Nh?t B?n dã du?c ráng giòn, t?o nên m?t huong v? d?c dáo và thom ngon.                                                                                                                                      ,monankhac6
                                                                                                                                                                                                                                                    ,Tempura                                                                                                                                                                                                                                                         ,         59
MK07     ,NGÔ M? XÀO TH?T HUN KHÓI
                                                                                                                                                                                                                                      ,       56000,Ngô M? du?c xào chín và k?t h?p v?i th?t hun khói, t?o nên m?t huong v? d?c trung và ngon mi?ng.                                                                                                                                                                ,monankhac7
                                                                                                                                                                                                                                                    ,Tempura                                                                                                                                                                                                                                                         ,         56
MK08     ,N?M XÀO T?NG H?P
                                                                                                                                                                                                                                              ,       86000,Các lo?i n?m tuoi ngon du?c xào chín m?m, k?t h?p v?i các lo?i rau và gia v?, t?o nên m?t món an giàu ch?t dinh du?ng.                                                                                                                                          ,monankhac8
                                                                                                                                                                                                                                                    ,Tempura                                                                                                                                                                                                                                                         ,         75
MK09     ,M? UDON H?I S?N
                                                                                                                                                                                                                                               ,      128000, M? udon m?m m?n du?c k?t h?p v?i các lo?i h?i s?n nhu tôm, m?c, cá... t?o nên m?t món an ngon và d?y d?c s?c.                                                                                                                                                  ,monankhac9
                                                                                                                                                                                                                                                    ,Tempura                                                                                                                                                                                                                                                         ,         52
MK10     ,CÁ H?I ÁP CH?O V?I TR?NG C? C?I
                                                                                                                                                                                                                               ,      128000,Mi?ng cá h?i tuoi ngon du?c áp ch?o giòn bên ngoài và m?m m?n bên trong, k?t h?p v?i l?p tr?ng và c? c?i t?o nên m?t huong v? d?c bi?t và thú v?.                                                                                                               ,monchien0
                                                                                                                                                                                                                                                     ,Tempura                                                                                                                                                                                                                                                         ,         96
MK11     ,CÁ KISU TEMPURA
                                                                                                                                                                                                                                               ,      168000,Cá kisu tempura là m?t món an truy?n th?ng Nh?t B?n. Cá kisu tuoi ngon du?c ch? bi?n thành tempura giòn r?m, k?t h?p v?i các lo?i rau tuoi và nu?c s?t m?m ngon.                                                                                                ,monchien1
                                                                                                                                                                                                                                                     ,Tempura                                                                                                                                                                                                                                                         ,         45
MK12     ,CÁ THI T?M B?T CÀ M? RÁN
                                                                                                                                                                                                                                      ,      168000,Mi?ng cá thi du?c t?m b?t cà mì và rán giòn, t?o nên m?t huong v? d?c trung và thú v?.                                                                                                                                                                          ,monchien2
                                                                                                                                                                                                                                                     ,Tempura                                                                                                                                                                                                                                                         ,         52
MK13     ,CÁNH GÀ T?M B?T CÀ MÌ RÁN
                                                                                                                                                                                                                                     ,      138000, Cánh gà du?c t?m b?t cà mì và rán giòn, t?o nên m?t huong v? d?c trung và thú v?. Món an này thu?ng du?c thu?ng th?c kèm v?i nu?c s?t và rau s?ng.                                                                                                             ,monchien3
                                                                                                                                                                                                                                                     ,Tempura                                                                                                                                                                                                                                                         ,         22
MK14     ,COM CHIÊN KI?U NH?T KÈM BÁCH QU? NU?NG
                                                                                                                                                                                                                        ,      118000, Com du?c chiên giòn và hòa quy?n v?i các lo?i rau, th?t và h?i s?n tuoi ngon, kèm theo mi?ng bách qu? nu?ng thom ngon.                                                                                                                                         ,monchien4
                                                                                                                                                                                                                                                     ,Tempura                                                                                                                                                                                                                                                         ,         88
MK15     ,KHOAI LANG T?M B?T RÁN
                                                                                                                                                                                                                                        ,       85000,Khoai lang du?c t?m b?t và rán giòn, t?o nên m?t huong v? d?c trung và thú v?.                                                                                                                                                                                  ,monchien5
                                                                                                                                                                                                                                                     ,Tempura                                                                                                                                                                                                                                                         ,         63
MK16     ,KHOAI TÂY CHIÊN
                                                                                                                                                                                                                                               ,       85000,Khoai tây chiên là m?t món an ph? bi?n và ngon mi?ng. Khoai tây du?c c?t thành mi?ng nh?, chiên giòn và gia v? theo kh?u v? cá nhân.                                                                                                                            ,monchien6
                                                                                                                                                                                                                                                     ,Tempura                                                                                                                                                                                                                                                         ,         45
MK17     ,KHOAI TÂY NGHI?N RAU T?M B?T CÀ M? RÁN
                                                                                                                                                                                                                        ,      138000,Khoai tây du?c nghi?n thành nhuy?n và t?m b?t cà mì, sau dó rán giòn và gia v? theo kh?u v?.                                                                                                                                                                    ,monchien7
                                                                                                                                                                                                                                                     ,Tempura                                                                                                                                                                                                                                                         ,         52
MK18     ,MU?C T?M B?T CÀ MÌ
                                                                                                                                                                                                                                            ,      190000,M?c du?c t?m b?t cà mì và rán giòn, t?o nên m?t huong v? d?c trung và thú v?.                                                                                                                                                                                   ,monchien9
                                                                                                                                                                                                                                                     ,Tempura                                                                                                                                                                                                                                                         ,         96
MK19     ,PHOMAI T?M B?T CÀ M? RÁN
                                                                                                                                                                                                                                      ,      108000,Phomai du?c t?m b?t cà mì và rán giòn, t?o nên m?t huong v? d?c trung và thú v?. Món an này thu?ng du?c thu?ng th?c kèm v?i nu?c s?t và rau s?ng.                                                                                                               ,monchien10
                                                                                                                                                                                                                                                    ,Tempura                                                                                                                                                                                                                                                         ,         12
ML01     ,CH? CÁ CHAY H?P
                                                                                                                                                                                                                                               ,       98000,Ch? cá du?c làm t? các thành ph?n chay, h?p trong nu?c và gia v?, t?o nên m?t huong v? d?c bi?t.                                                                                                                                                                ,monlau1
                                                                                                                                                                                                                                                       ,Hotpot                                                                                                                                                                                                                                                          ,         45
ML02     ,CH? CÁ Ð?
                                                                                                                                                                                                                                                     ,       98000,Món an truy?n th?ng du?c ch? bi?n t? th?t cá d? tuoi ngon, du?c chiên giòn và có huong v? d?m dà.                                                                                                                                                               ,monlau2
                                                                                                                                                                                                                                                       ,Hotpot                                                                                                                                                                                                                                                          ,         63
ML03     ,CON V?M BI?N
                                                                                                                                                                                                                                                  ,      180000,V?m bi?n du?c ch? bi?n theo yêu câ`u cu?a quy´ kha´ch, t?o nên m?t tr?i nghi?m ?m th?c d?c bi?t.                                                                                                                                                                ,monlau3
                                                                                                                                                                                                                                                       ,Hotpot                                                                                                                                                                                                                                                          ,         63
ML04     ,CÁ CHÌNH
                                                                                                                                                                                                                                                      ,      300000,Th?t cá chình có v? ng?t và thom, duo?c chê´ biê´n theo công thu´c lâu do`i cu?a nha` ha`ng chu´ng tôi, hu´a he?n se~ la`m ba?n bâ´t ngo` bo?i huong vi? da?c biê?t cu?a no´.                                                                                   ,monlau4
                                                                                                                                                                                                                                                       ,Hotpot                                                                                                                                                                                                                                                          ,         63
ML05     ,CÁ H?I TUOI
                                                                                                                                                                                                                                                   ,      208000,Th?t cá h?i tuoi ngon, m?m m?n và có huong v? d?c trung. Chúng tôi ch? bi?n cá h?i tuoi thành nhi?u món nhu sashimi, nu?ng, h?p ho?c cu?n sushi.                                                                                                                ,monlau5
                                                                                                                                                                                                                                                       ,Hotpot                                                                                                                                                                                                                                                          ,         33
ML08     ,HÀU NH?T
                                                                                                                                                                                                                                                      ,      188000,Chúng tôi ph?c v? hàu Nh?t theo nhi?u cách ch? bi?n khác nhau nhu h?p, nu?ng ho?c chiên. Hàu có v? ng?t t? nhiên và m?t huong v? d?c trung.                                                                                                                     ,monlau6
                                                                                                                                                                                                                                                       ,Hotpot                                                                                                                                                                                                                                                          ,         56
ML09     ,KHOAI MÔN 
                                                                                                                                                                                                                                                    ,       58000,Khoai môn có v? ng?t t? nhiên và m?t chút com d?o.                                                                                                                                                                                                              ,monlau7
                                                                                                                                                                                                                                                       ,Hotpot                                                                                                                                                                                                                                                          ,         25
ML10     ,L?U BÒ M? NHÚNG 
                                                                                                                                                                                                                                              ,      780000,Th?t bò M? tuoi ngon du?c nhúng trong nu?c l?u nóng h?i, k?t h?p v?i các lo?i rau c? tuoi ngon. Ðây là m?t món an thích h?p d? chia s? v?i gia dình và b?n bè.                                                                                                  ,monlau8
                                                                                                                                                                                                                                                       ,Hotpot                                                                                                                                                                                                                                                          ,         23
ML11     ,L?U BÒ WAGYU
                                                                                                                                                                                                                                                  ,      990000,Th?t bò Wagyu d?c bi?t và thom ngon du?c nhúng trong n?i l?u nóng h?i, t?o nên m?t huong v? d?m dà và tuy?t v?i. Ðây là m?t tr?i nghi?m ?m th?c dáng nh?.                                                                                                       ,monlau9
                                                                                                                                                                                                                                                       ,Hotpot                                                                                                                                                                                                                                                          ,         63
ML12     ,L?U CHAY
                                                                                                                                                                                                                                                      ,      468000, Chúng tôi ch? bi?n l?u chay t? các lo?i rau c? tuoi ngon, n?m và d?u h?, k?t h?p v?i nu?c l?u d?m dà và thom ngon. Món này là l?a ch?n hoàn h?o d? thu?ng th?c huong v? chay tr?n v?n.                                                                         ,monlau10
                                                                                                                                                                                                                                                      ,Hotpot                                                                                                                                                                                                                                                          ,         62
ML13     ,L?U CUA G?CH
                                                                                                                                                                                                                                                  ,      468000,Cua g?ch tuoi ngon du?c ch? bi?n trong n?i l?u nóng h?i, k?t h?p v?i các lo?i rau c? và gia v? t?o nên m?t huong v? d?m dà và ngon mi?ng.                                                                                                                       ,monlau11
                                                                                                                                                                                                                                                      ,Hotpot                                                                                                                                                                                                                                                          ,         36
ML14     ,L?U GI?Y CÁ H?I TUOI
                                                                                                                                                                                                                                          ,      480000, Cá h?i tuoi ngon du?c gói trong gi?y b?c và nu?ng trên b?p than, t?o nên m?t món an thom ngon và d?c bi?t.                                                                                                                                                     ,monlau12
                                                                                                                                                                                                                                                      ,Hotpot                                                                                                                                                                                                                                                          ,         45
MN01     ,TH?T L?N NH?T CU?N KIMCHI XIÊN NU?NG
                                                                                                                                                                                                                          ,       76000,M?t món an d?c dáo và thú v?, k?t h?p gi?a th?t l?n Nh?t và kimchi cu?n thành xiên, du?c nu?ng giòn và thom ngon.                                                                                                                                               ,monnuong01
                                                                                                                                                                                                                                                    ,Grilled                                                                                                                                                                                                                                                         ,        112
MN02     ,HÀU TUOI NU?NG TH?U HUN KHÓI, HÀNH TÂY, PHOMAT
                                                                                                                                                                                                                ,       46000,M?t món h?p d?n v?i hàu tuoi ngon du?c nu?ng th?u và hòa quy?n v?i hành tây và phomat, t?o nên m?t huong v? d?c dáo.                                                                                                                                            ,monnuong02                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,         96
MN03     ,COM CU?N TÔM TEMPURA NU?NG
                                                                                                                                                                                                                                    ,      108000,M?t món com cu?n ngon mi?ng v?i tôm tempura nu?ng, t?o nên m?t huong v? giòn ngon và d?m dà.                                                                                                                                                                    ,monnuong03                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,         86
MN04     ,CÁNH GÀ NU?NG GIÒN V?I S?T TERI
                                                                                                                                                                                                                               ,       78000,S?a caramel macchiato                                                                                                                                                                                                                                           ,monnuong04                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,        105
MN05     ,CÁ THU ÐAO VÀ T?I TÂY NU?NG MU?N HO?C S?T TERI
                                                                                                                                                                                                                ,       58000,S?a matcha macchiato                                                                                                                                                                                                                                            ,monnuong05                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,         63
MN06     ,XÚC XÍCH L?N NH?T
                                                                                                                                                                                                                                             ,       46000,Sinh t? dua h?u                                                                                                                                                                                                                                                 ,monnuong06                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,         10
MN07     ,XIÊN NU?NG T?NG H?P
                                                                                                                                                                                                                                           ,       42000,Nu?c chanh s? m?t ong                                                                                                                                                                                                                                           ,monnuong07                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,         96
MN08     ,TR?NG CÁ TUY?T NU?NG 
                                                                                                                                                                                                                                         ,       69000, Tr?ng cá tuy?t tuoi ngon du?c nu?ng v?a d?, t?o nên m?t món an d?c dáo và thom ngon.                                                                                                                                                                           ,monnuong08
                                                                                                                                                                                                                                                    ,Grilled                                                                                                                                                                                                                                                         ,         21
MN09     ,TH?T HUN KHÓ CU?N TÔM NU?NG 
                                                                                                                                                                                                                                  ,       59000,Th?t hun khói cu?n cùng tôm nu?ng, t?o nên m?t món cu?n h?p d?n và d?m dà.                                                                                                                                                                                      ,monnuong09                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,         45
MN10     ,TH? HUN KHÓI CU?N MANG TÂY NU?NG MU?I
                                                                                                                                                                                                                         ,       57000,Th?t hun khói cu?n v?i mang tây, du?c nu?ng giòn và u?p mu?i, mang d?n m?t huong v? d?c dáo và thú v?.                                                                                                                                                          ,monnuong10                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,         96
MN11     ,TH?T HUN KHÓI CU?N KHOAI TÂY NU?NG MU?I
                                                                                                                                                                                                                       ,       64000,Th?t hun khói cu?n v?i khoai tây, du?c nu?ng giòn và u?p mu?i, t?o nên m?t món an ngon mi?ng và d?m dà.                                                                                                                                                         ,monnuong11                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,         27
MN12     ,TH?T GÀ XIÊN NU?NG MU?I HO?C S?T TERI
                                                                                                                                                                                                                         ,       57000,Th?t gà du?c xiên và nu?ng giòn v?i v? mu?i ho?c s?t teri thom ngon, mang d?n m?t huong v? tuy?t v?i và d?m dà.                                                                                                                                                 ,monnuong12                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,         29
MN13     ,TH?T GÀ T?I TÂY XIÊN NU?NG MU?I HO?C S?T TERI
                                                                                                                                                                                                                 ,       46000,Th?t gà du?c xiên và nu?ng v?i t?i tây, t?o nên m?t huong v? d?c bi?t và thú v? v?i s? k?t h?p c?a mu?i ho?c s?t teri.                                                                                                                                          ,monnuong13                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,        108
MN14     ,TH?T BÒ ÚC NU?NG V?I S?T TERI
                                                                                                                                                                                                                                 ,      299000,V?a Bò viên ki?u Ý, v?a th?t bò thu?ng h?ng. C?n m?t mi?ng thôi là c?m nh?n du?c v? m?m ng?t!                                                                                                                                                                   ,monnuong14                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,         12
MN15     ,TH?T BA CH? NU?NG S?T MISO
                                                                                                                                                                                                                                    ,      145000,H?i s?n ph?i cay thì m?i ngon. Chính là b?a ti?c ki?u Singapore d?m v?!!!                                                                                                                                                                                       ,monnuong15                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,         41
MN16     ,T?I NU?NG MU?I
                                                                                                                                                                                                                                                ,      250000,T?i du?c nu?ng giòn v?i v? mu?i, t?o nên m?t món an thom ngon và d?m dà.                                                                                                                                                                                        ,monnuong16                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,         83
MN17     ,SU?NG BÒ M? NU?NG S?T TIÊU ÐEN
                                                                                                                                                                                                                                ,      169000,Su?n bò M? du?c nu?ng chín m?m, kèm theo s?t tiêu den thom ngon, mang d?n m?t huong v? tuy?t v?i và d?c bi?t.                                                                                                                                                   ,monnuong17                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,         96
MN18     ,S?N GÀ NU?NG MU?I
                                                                                                                                                                                                                                             ,      230000,S?n gà du?c nu?ng giòn v?i v? mu?i, t?o nên m?t món an ngon mi?ng và d?m dà.                                                                                                                                                                                    ,monnuong18                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,         15
MN19     ,SÒ ÐI?P NU?NG MU?I HO?C S?T TERI
                                                                                                                                                                                                                              ,      129000, Sò di?p du?c nu?ng giòn v?i v? mu?i ho?c s?t teri thom ngon, mang d?n m?t huong v? d?c dáo và thú v?.                                                                                                                                                          ,monnuong19                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,         56
MN20     ,N?M HUONG TUOI NH?I TH?T NU?NG 
                                                                                                                                                                                                                               ,      155000,N?m huong tuoi ngon du?c nh?i v?i th?t và nu?ng giòn, t?o nên m?t món an h?p d?n và d?c bi?t.                                                                                                                                                                   ,monnuong20                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,         85
MN21     ,M?C ?NG NU?NG MU?I HO?C S?T TERI
                                                                                                                                                                                                                              ,      129000,M?c ?ng du?c nu?ng giòn v?i v? mu?i ho?c s?t teri, mang d?n m?t huong v? tuy?t v?i và thú v?.                                                                                                                                                                   ,monnuong21                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,         23
MN22     ,M? GÀ XIÊN NU?NG MU?I HO?C S?T TERI
                                                                                                                                                                                                                           ,       99000,M? gà du?c xiên và nu?ng v?i v? mu?i ho?c s?t teri thom ngon, t?o nên m?t món an ngon mi?ng và d?m dà.                                                                                                                                                          ,monnuong22                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,         96
MN23     ,LUON NH?T XIÊN NU?NG S?T TERI
                                                                                                                                                                                                                                 ,      169000, Luon nh?t tuoi ngon du?c xiên và nu?ng v?i s?t teri thom ngon, mang d?n m?t huong v? d?c bi?t và thú v?.                                                                                                                                                       ,monnuong23                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,         78
MN28     ,DA GÀ XIÊN NU?NG MU?I
                                                                                                                                                                                                                                         ,       98000,Da gà du?c xiên và nu?ng giòn v?i v? mu?i, t?o nên m?t món an thom ngon và d?c bi?t.                                                                                                                                                                            ,monnuong28                                                                                                                                                                                                                                                      ,Grilled                                                                                                                                                                                                                                                         ,         56

(90 rows affected)
